version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling app.java
      - javac src/App.java
      - echo run build
      - jar -cf filemanager.jar src/App.class
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
     - filemanager.jar
